<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TrainingRuntimeIdentifier Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</TrainingRuntimeIdentifier>
    <TrainingRuntimeIdentifier Condition="'$(TrainingRuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</TrainingRuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Training.Application\Training.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <TrainingRuntimeModule Include="..\Training.Infrastructure\Training.Infrastructure.csproj" />
    <TrainingRuntimeModule Include="..\Training.Strava\Training.Strava.csproj" />
  </ItemGroup>

  <Target Name="PublishTrainingRuntimeModules" BeforeTargets="Build">
    <MSBuild Projects="@(TrainingRuntimeModule)" Targets="Publish" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);PublishDir=$(MSBuildProjectDirectory)/$(IntermediateOutputPath)training-runtime-modules/;UseAppHost=false" />
  </Target>

  <Target Name="CopyTrainingRuntimeModules" AfterTargets="Build">
    <ItemGroup>
      <TrainingRuntimeModuleOutput Include="$(IntermediateOutputPath)training-runtime-modules/**/*.*" />
      <TrainingRuntimeModuleNativeOutput Include="$(IntermediateOutputPath)training-runtime-modules/runtimes/$(TrainingRuntimeIdentifier)/native/*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TrainingRuntimeModuleOutput)" DestinationFiles="@(TrainingRuntimeModuleOutput->'$(OutputPath)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(TrainingRuntimeModuleNativeOutput)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyTrainingRuntimeModulesToPublish" AfterTargets="Publish">
    <ItemGroup>
      <TrainingRuntimeModulePublishOutput Include="$(IntermediateOutputPath)training-runtime-modules/**/*.*" />
      <TrainingRuntimeModuleNativePublishOutput Include="$(IntermediateOutputPath)training-runtime-modules/runtimes/$(TrainingRuntimeIdentifier)/native/*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TrainingRuntimeModulePublishOutput)" DestinationFiles="@(TrainingRuntimeModulePublishOutput->'$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(TrainingRuntimeModuleNativePublishOutput)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
