using Npgsql;
using Training.Domain.Entities;
using Training.Domain.Enums;
using Training.Application.Abstractions;

namespace Training.Infrastructure.Persistence;

public sealed class PostgresWorkoutRepository(NpgsqlDataSource dataSource) : IWorkoutRepository
{
    private readonly SemaphoreSlim _schemaLock = new(1, 1);
    private bool _schemaEnsured;

    public async Task SaveWeeklyPlanAsync(
        IReadOnlyList<WorkoutDay> workouts,
        CancellationToken cancellationToken = default)
    {
        await EnsureSchemaAsync(cancellationToken);

        await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);

        await using (var deleteCommand = new NpgsqlCommand("DELETE FROM workout_days;", connection, transaction))
        {
            await deleteCommand.ExecuteNonQueryAsync(cancellationToken);
        }

        foreach (var workout in workouts.OrderBy(workout => workout.Date))
        {
            await SaveWorkoutAsync(connection, transaction, workout, cancellationToken);
        }

        await transaction.CommitAsync(cancellationToken);
    }

    public async Task<IReadOnlyList<WorkoutDay>> GetCurrentWeekAsync(CancellationToken cancellationToken = default)
    {
        await EnsureSchemaAsync(cancellationToken);

        await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
        var workoutRows = await LoadWorkoutRowsAsync(connection, cancellationToken);
        var exercisesByDate = await LoadExercisesAsync(connection, cancellationToken);

        return workoutRows
            .Select(row => new WorkoutDay(
                row.Date,
                row.WorkoutType,
                exercisesByDate.GetValueOrDefault(row.Date, []),
                row.DurationMinutes,
                row.Intensity,
                row.Notes))
            .ToList();
    }

    private async Task EnsureSchemaAsync(CancellationToken cancellationToken)
    {
        if (_schemaEnsured)
        {
            return;
        }

        await _schemaLock.WaitAsync(cancellationToken);

        try
        {
            if (_schemaEnsured)
            {
                return;
            }

            await using var connection = await dataSource.OpenConnectionAsync(cancellationToken);
            await using var command = new NpgsqlCommand(
                """
                CREATE TABLE IF NOT EXISTS workout_days (
                    workout_date date PRIMARY KEY,
                    workout_type text NOT NULL,
                    duration_minutes integer NOT NULL,
                    intensity text NOT NULL,
                    notes text NULL
                );

                CREATE TABLE IF NOT EXISTS exercises (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workout_date date NOT NULL REFERENCES workout_days(workout_date) ON DELETE CASCADE,
                    sort_order integer NOT NULL,
                    name text NOT NULL,
                    sets integer NOT NULL,
                    reps text NOT NULL,
                    rir_or_rpe text NULL
                );

                CREATE TABLE IF NOT EXISTS exercise_muscle_groups (
                    exercise_id bigint NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
                    sort_order integer NOT NULL,
                    muscle_group text NOT NULL,
                    PRIMARY KEY (exercise_id, sort_order)
                );
                """,
                connection);

            await command.ExecuteNonQueryAsync(cancellationToken);
            _schemaEnsured = true;
        }
        finally
        {
            _schemaLock.Release();
        }
    }

    private static async Task SaveWorkoutAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        WorkoutDay workout,
        CancellationToken cancellationToken)
    {
        await using (var command = new NpgsqlCommand(
            """
            INSERT INTO workout_days (workout_date, workout_type, duration_minutes, intensity, notes)
            VALUES (@date, @workout_type, @duration_minutes, @intensity, @notes);
            """,
            connection,
            transaction))
        {
            command.Parameters.AddWithValue("date", workout.Date);
            command.Parameters.AddWithValue("workout_type", workout.WorkoutType.ToString());
            command.Parameters.AddWithValue("duration_minutes", workout.DurationMinutes);
            command.Parameters.AddWithValue("intensity", workout.Intensity.ToString());
            command.Parameters.AddWithValue("notes", (object?)workout.Notes ?? DBNull.Value);

            await command.ExecuteNonQueryAsync(cancellationToken);
        }

        for (var exerciseIndex = 0; exerciseIndex < workout.Exercises.Count; exerciseIndex++)
        {
            var exercise = workout.Exercises[exerciseIndex];
            var exerciseId = await SaveExerciseAsync(
                connection,
                transaction,
                workout.Date,
                exercise,
                exerciseIndex,
                cancellationToken);

            await SaveMuscleGroupsAsync(
                connection,
                transaction,
                exerciseId,
                exercise.MuscleGroups,
                cancellationToken);
        }
    }

    private static async Task<long> SaveExerciseAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        DateOnly workoutDate,
        Exercise exercise,
        int sortOrder,
        CancellationToken cancellationToken)
    {
        await using var command = new NpgsqlCommand(
            """
            INSERT INTO exercises (workout_date, sort_order, name, sets, reps, rir_or_rpe)
            VALUES (@workout_date, @sort_order, @name, @sets, @reps, @rir_or_rpe)
            RETURNING id;
            """,
            connection,
            transaction);

        command.Parameters.AddWithValue("workout_date", workoutDate);
        command.Parameters.AddWithValue("sort_order", sortOrder);
        command.Parameters.AddWithValue("name", exercise.Name);
        command.Parameters.AddWithValue("sets", exercise.Sets);
        command.Parameters.AddWithValue("reps", exercise.Reps);
        command.Parameters.AddWithValue("rir_or_rpe", (object?)exercise.RirOrRpe ?? DBNull.Value);

        var exerciseId = await command.ExecuteScalarAsync(cancellationToken);
        return (long)exerciseId!;
    }

    private static async Task SaveMuscleGroupsAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        long exerciseId,
        IReadOnlyList<MuscleGroup> muscleGroups,
        CancellationToken cancellationToken)
    {
        for (var muscleGroupIndex = 0; muscleGroupIndex < muscleGroups.Count; muscleGroupIndex++)
        {
            await using var command = new NpgsqlCommand(
                """
                INSERT INTO exercise_muscle_groups (exercise_id, sort_order, muscle_group)
                VALUES (@exercise_id, @sort_order, @muscle_group);
                """,
                connection,
                transaction);

            command.Parameters.AddWithValue("exercise_id", exerciseId);
            command.Parameters.AddWithValue("sort_order", muscleGroupIndex);
            command.Parameters.AddWithValue("muscle_group", muscleGroups[muscleGroupIndex].ToString());

            await command.ExecuteNonQueryAsync(cancellationToken);
        }
    }

    private static async Task<IReadOnlyList<WorkoutRow>> LoadWorkoutRowsAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        var workouts = new List<WorkoutRow>();

        await using var command = new NpgsqlCommand(
            """
            SELECT workout_date, workout_type, duration_minutes, intensity, notes
            FROM workout_days
            ORDER BY workout_date;
            """,
            connection);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        while (await reader.ReadAsync(cancellationToken))
        {
            workouts.Add(new WorkoutRow(
                reader.GetFieldValue<DateOnly>(0),
                Enum.Parse<WorkoutType>(reader.GetString(1)),
                reader.GetInt32(2),
                Enum.Parse<IntensityLevel>(reader.GetString(3)),
                reader.IsDBNull(4) ? null : reader.GetString(4)));
        }

        return workouts;
    }

    private static async Task<IReadOnlyDictionary<DateOnly, IReadOnlyList<Exercise>>> LoadExercisesAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        var exercisesByDate = new Dictionary<DateOnly, List<Exercise>>();

        await using var command = new NpgsqlCommand(
            """
            SELECT
                e.workout_date,
                e.name,
                e.sets,
                e.reps,
                e.rir_or_rpe,
                COALESCE(
                    ARRAY_AGG(mg.muscle_group ORDER BY mg.sort_order)
                        FILTER (WHERE mg.muscle_group IS NOT NULL),
                    ARRAY[]::text[]
                ) AS muscle_groups
            FROM exercises e
            LEFT JOIN exercise_muscle_groups mg ON mg.exercise_id = e.id
            GROUP BY e.id, e.workout_date, e.sort_order, e.name, e.sets, e.reps, e.rir_or_rpe
            ORDER BY e.workout_date, e.sort_order;
            """,
            connection);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);

        while (await reader.ReadAsync(cancellationToken))
        {
            var workoutDate = reader.GetFieldValue<DateOnly>(0);
            var muscleGroups = reader
                .GetFieldValue<string[]>(5)
                .Select(value => Enum.Parse<MuscleGroup>(value))
                .ToList();
            var exercise = new Exercise(
                reader.GetString(1),
                reader.GetInt32(2),
                reader.GetString(3),
                reader.IsDBNull(4) ? null : reader.GetString(4),
                muscleGroups);

            if (!exercisesByDate.TryGetValue(workoutDate, out var exercises))
            {
                exercises = [];
                exercisesByDate[workoutDate] = exercises;
            }

            exercises.Add(exercise);
        }

        return exercisesByDate.ToDictionary(
            pair => pair.Key,
            pair => (IReadOnlyList<Exercise>)pair.Value);
    }

    private sealed record WorkoutRow(
        DateOnly Date,
        WorkoutType WorkoutType,
        int DurationMinutes,
        IntensityLevel Intensity,
        string? Notes);
}
